// Hap - the simple and effective provisioner
// Copyright (c) 2015 Garrett Woodworth (https://github.com/gwoo)
// The BSD License http://opensource.org/licenses/bsd-license.php.

package cli

import (
	"fmt"

	"github.com/gwoo/hap"
)

// Add the build command
func init() {
	Commands.Add("build", &BuildCmd{})
}

type BuildCmd struct {
	result []byte
	log    string
	build  string
}

// Does this command expect a remote
func (cmd *BuildCmd) IsRemote() bool {
	return true
}

// Return the result of the command
func (cmd *BuildCmd) String() string {
	return string(cmd.result)
}

// Return the log generated by the command
func (cmd *BuildCmd) Log() string {
	return cmd.log
}

// Get help on the build command
func (cmd *BuildCmd) Help() string {
	return "hap build\tRun the builds and commands from the Hapfile."
}

// Run the build command on the remote host
func (cmd *BuildCmd) Run(remote *hap.Remote) error {
	result, err := remote.Build()
	cmd.result = result
	if err != nil {
		cmd.log = fmt.Sprintf("Build failed %s on %s.", cmd.build, remote.Host.Addr)
		return err
	}
	cmd.log = fmt.Sprintf("Build %s on %s.", cmd.build, remote.Host.Addr)
	return nil
}
