// Hap - the simple and effective provisioner
// Copyright (c) 2014 Garrett Woodworth (https://github.com/gwoo)
// The BSD License http://opensource.org/licenses/bsd-license.php.

package cli

import (
	"flag"
	"fmt"
	"os"
	"os/exec"
	"os/user"

	"github.com/gwoo/hap"
)

// Add the create command
func init() {
	Commands.Add("create", &CreateCmd{})
}

// Init command for setting up remote repo
type CreateCmd struct {
	result []byte
	log    string
}

// Does this command expect a remote
func (cmd *CreateCmd) IsRemote() bool {
	return false
}

// Return the result of the command
func (cmd *CreateCmd) String() string {
	return string(cmd.result)
}

// Return the log generated by the command
func (cmd *CreateCmd) Log() string {
	return cmd.log
}

// Get help on the create command
func (cmd *CreateCmd) Help() string {
	return "hap create <name>\tCreate a new Hapfile at <name>."
}

// Run the command against the remote
func (cmd *CreateCmd) Run(remote *hap.Remote) error {
	args := flag.Args()
	if len(args) <= 1 {
		return fmt.Errorf("error: expects <name>")
	}
	work := flag.Arg(1)
	err := os.MkdirAll(work, os.ModePerm|os.ModeDir)
	if err != nil {
		cmd.log = fmt.Sprintf("Failed to create %s.", work)
		return err
	}
	c := exec.Command("git", "init", ".")
	c.Dir = work
	result, err := c.CombinedOutput()
	cmd.result = result
	if err != nil {
		cmd.log = fmt.Sprintf("Failed to create %s.", work)
		return err
	}
	file, err := os.OpenFile(work+"/Hapfile", os.O_CREATE|os.O_RDWR|os.O_APPEND, 0660)
	if err != nil {
		cmd.log = fmt.Sprintf("Failed to create %s.", work+"/Hapfile")
	}
	file.WriteString("[default]\n")
	if u, err := user.Current(); err == nil {
		file.WriteString(fmt.Sprintf("username = \"%s\"\n", u.Username))
	}
	if _, err := hap.NewKeyFile("~/.ssh/id_rsa"); err == nil {
		file.WriteString(fmt.Sprintf("identity = \"%s\"\n", "~/.ssh/id_rsa"))
	}
	cmd.log = fmt.Sprintf("Created %s.", work)
	return nil
}
